Fixed IOError when ``setup.cfg`` is missing and no version is found.
Traceback (most recent call last):
  File "/Users/maurits/tools/bin/prerelease", line 45, in <module>
    sys.exit(zest.releaser.prerelease.main())
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 104, in main
    prereleaser.run()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 353, in run
    self.execute()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 68, in execute
    self._write_version()
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 283, in _write_version
    self.vcs.version = self.data['new_version']
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/vcs.py", line 275, in _update_version
    setup_cfg_lines, encoding = utils.read_text_file('setup.cfg')
  File "/Users/maurits/tools/src/zest.releaser/zest/releaser/utils.py", line 117, in read_text_file
    with open(filename, 'rb') as filehandler:
IOError: [Errno 2] No such file or directory: u'setup.cfg'