Support Python 3.14.
No changes were needed.
We do get some extra ResourceWarnings:

```
.../lib/python3.14/tempfile.py:484: ResourceWarning:
Implicitly cleaning up <HTTPError 404: 'HTTP Error 404: Not Found (tha.example does not have any releases)'>
```

I tried fixing that, which worked on 3.14, but it failed on 3.9:

```
File "/Users/maurits/community/zest.releaser/zest/releaser/tests/bumpversion.txt", line 33, in bumpversion.txt
Failed example:
    fullrelease.main()
Exception raised:
    Traceback (most recent call last):
      File "/Users/maurits/.pyenv/versions/3.9.22/lib/python3.9/doctest.py", line 1334, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest bumpversion.txt[10]>", line 1, in <module>
        fullrelease.main()
      File "/Users/maurits/community/zest.releaser/zest/releaser/fullrelease.py", line 27, in main
        releaser.run()
      File "/Users/maurits/community/zest.releaser/zest/releaser/baserelease.py", line 427, in run
        self.execute()
      File "/Users/maurits/community/zest.releaser/zest/releaser/release.py", line 140, in execute
        self._release()
      File "/Users/maurits/community/zest.releaser/zest/releaser/release.py", line 384, in _release
        self._upload_distributions(package)
      File "/Users/maurits/community/zest.releaser/zest/releaser/release.py", line 240, in _upload_distributions
        if not self._ask_upload(package, server, register):
      File "/Users/maurits/community/zest.releaser/zest/releaser/release.py", line 259, in _ask_upload
        if server == "pypi" and not package_in_pypi(package):
      File "/Users/maurits/community/zest.releaser/zest/releaser/release.py", line 56, in package_in_pypi
        request.urlopen(url)
      File "/Users/maurits/community/zest.releaser/zest/releaser/tests/functional.py", line 47, in _mock_urlopen
        with HTTPError(
      File "/Users/maurits/.pyenv/versions/3.9.22/lib/python3.9/urllib/response.py", line 29, in __enter__
        if self.fp.closed:
    AttributeError: 'NoneType' object has no attribute 'closed'
```

So I left the code as it was, and added a comment.