Adjusted (unused?) intersphinx mapping to the new syntax
RTD complained about this:

ERROR: Invalid value `None` in intersphinx_mapping['http://docs.python.org/']. Expected a two-element tuple or list.