Sort buildout versions alphabetically, case insensitive.
The build fails with a version conflict, so let's first sort the versions:

```
Got chardet 4.0.0.
Version and requirements information containing chardet:
  Requirement of zest.releaser[recommended]: chardet
  Requirement of requests: chardet<3.1.0,>=3.0.2
While:
  Updating script.
Error: There is a version conflict.
We already have: chardet 4.0.0
but requests 2.22.0 requires 'chardet<3.1.0,>=3.0.2'.
```